version: '3.4'

services:
  db:
    environment:
      - SA_PASSWORD=Passw0rd!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"    # Important: In a production environment your should remove the external port

  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5101:80" 
      - "5102:443" 
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
